version: '3.7'

services:
  consul:
    image: consul
    container_name: consul
    restart: always
    networks:
      - orange-developer
    ports:
    - "8500:8500"
    - "8600:8600/tcp"
    - "8600:8600/udp"
    command: "agent -dev"

  user-service:
    build:
      context: user-microservice
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/userServiceDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    networks:
      - orange-developer



  db:
    image: mysql
    ports:
    - "3307:3307"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./init:/docker-entrypoint-initdb.d

networks:
  orange-developer:
    driver: bridge